# Generated by Django 4.0.4 on 2022-06-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
